name: barcode_reader_webassembly_example
description: Barcode reader using zbar and webassembly.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  barcode_reader_webassembly:
    path: ../
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - integration_test/__mock__/assets/
