name: barcode_reader_webassembly
description: A flutter web plugin to read barcode using webassembly and zbar.
version: 0.0.7
homepage: https://github.com/emirdeliz/barcode_reader_webassembly

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    # These assets are compiled from the project Barcode Read - Ts and Webassembly.
    # https://github.com/emirdeliz/barcode-reader-zbar-webassembly.
    - assets/barcode-reader.js
    - assets/barcode-reader.wasm
  plugin:
    platforms:
      web:
        pluginClass: BarcodeReaderWebassemblyWeb
        fileName: barcode_reader_webassembly_web.dart
