name: barcode_reader_webassembly
description: A flutter web plugin to read barcode using webassembly and zbar.
version: 0.0.8
homepage: https://github.com/emirdeliz/barcode_reader_webassembly

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dart_web_plugin_base: 
  js: ^0.6.5
  plugin_platform_interface: ^2.0.2
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4

flutter:
  assets:
    - assets/
  plugin:
    platforms:
      web:
        pluginClass: BarcodeReaderWebassemblyPlugin
        fileName: barcode_reader_webassembly_plugin.dart
