name: Install chrome & chromedriver
description: Install chrome & chromedriver
runs:
  using: 'composite'
  steps:
    - name: Installing chrome
      run: sudo sh ./scripts/exec-chrome-install.sh
      shell: sh
    - name: Installing chromedriver
      run: sudo sh ./scripts/exec-chromedriver-install.sh
      shell: sh
    - uses: nanasess/setup-chromedriver@v1
    - run: |
        export DISPLAY=:99
        chromedriver --disable-gpu --port=4444 --url-base=/wd/hub --whitelisted-ips= &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      shell: sh
