name: Lint
on: [push]
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
          architecture: x64
      - run: flutter analyze
