name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: emirdeliz/emirdeliz-chromedriver@v0.0.6
        with:
          download-path: example/driver_test
          version: 114.0.5735.90
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
          architecture: x64
      - run: flutter --version
      - run: cd example && sh scripts/run-integration-test.sh
